version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - run: make
      - store_artifacts:
          path: Chainer.docset.zip
      - persist_to_workspace:
          root: .
          paths:
            - .venv
            - Chainer.docset.zip
            - Makefile
            - requirements.txt
  release:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - attach_workspace:
          at: .
      - run: make release

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
